# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace cardano-ios.xcworkspace -scheme cardano-ios-example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
